### ISSUE TITLE
No way to omit integer fields with "omitempty" without pointer indirection

### ISSUE THREAD

**Issue by Crazy-Owl** [mxmCherry/openrtb#10]
Currently there's no way to omit/not-omit fields like `secure` (in Impression) from JSON-representation of  BidRequest regardless of the actual value (i.e. distinguish between field value and exporting the field).

Let's take `Secure` from `Imp` for example. The field in question is defined as following:

```
Secure int8 `json:"secure,omitempty"`
```

Some DSPs are unable to process this field properly due to the way they implement OpenRTB protocol, so it would be nice to omit this field from Imp altogether in such case. Or vice versa -- DSP can _require_ the field to be present, even if it has a value of 0. However, without pointer indirection there's no way to add/remove it reliably. A value of `0` will never be exported in resulting JSON if DSP requires it ("omitempty" `int8` field won't be included to JSON if it has value of 0).

So in my opinion it would be better to use pointer indirection here in all these clauses to distinguish between "empty" and "not-empty" for "omitempty" fields.

**Comment by mxmCherry** [comment]
I'm not opposed to pointers usage, even more - here's the first step to switch such fields: https://github.com/mxmCherry/openrtb/pull/9

If OpenRTB describes special treatment for value absence - I have no objections in changing it to pointer.

If field defaults to zero or it is an enum without zero values - better keep it non-pointer.

Regarding `Impression.secure`:

> If omitted, the secure state is unknown, but non-secure HTTP support can be assumed.

I don't really think, that DSP can seriously benefit from zero value being explicitly sent, but I'm Ok to provide SSPs an ability to behave in "ideal" way.

So, if you'll submit PR - that would be nice. But, please, don't switch all such fields in one go - let's do only what you need *right now*.

**Comment by mxmCherry** [comment]
PR https://github.com/mxmCherry/openrtb/pull/11 merged, released as [v6.0.0](https://github.com/mxmCherry/openrtb/releases/tag/v6.0.0)

Thanks for contributing!
