### ISSUE TITLE
Improve typesafety

### ISSUE THREAD

**Issue by dbemiller** [mxmCherry/openrtb#15]
There are many values in the OpenRTB spec which define more narrow "legal" values than Go's native types. Some examples:

- [Test mode](https://github.com/mxmCherry/openrtb/blob/master/bid_request.go#L76)
- [AllImps](https://github.com/mxmCherry/openrtb/blob/master/bid_request.go#L134)
- [FD](https://github.com/mxmCherry/openrtb/blob/master/source.go#L19)

In my opinion, it'd be really nice if there were typedefs for all these values. For example, something like this:

```
type FD int8
const (
	EXCHANGE FD = iota
	UPSTREAM_SOURCE
)

func (fd FD) MarshalJSON() ([]byte, error) {
	switch fd {
	case EXCHANGE:
		return []byte("0"), nil
	case UPSTREAM_SOURCE:
		return []byte("1"), nil
	default:
		return nil, errors.New("FD must be 0 or 1")
	}
}

func (fd *FD) UnmarshalJSON(data []byte) error {
	var tmp int8
	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	} else {
		switch tmp {
		case 0:
			*fd = EXCHANGE
			return nil
		case 1:
			*fd = UPSTREAM_SOURCE
			return nil
		default:
			return fmt.Errorf("Cannot turn %d into an FD", tmp)
		}
	}
}
```

That way, the compiler would discourage people from sending invalid values in their messages. Any remaining bugs (e.g. if a caller does `FD(3)`) would get runtime errors when they try to marshal the objects. It also makes calling code more readable, since they'll be using your named constants.

What do you think?

**Comment by mxmCherry** [comment]
Already thought about it.

I've already drafted type-safe enums (described in section 5; haven't pushed that branch yet, want to polish it first). But don't expect it to be merged/released in next 2-3 weeks.

Later I will defo look into making types/constants for other fields (that are effectively enums, but not listed in section 5).

But hand-crafted (un)marshalers - that's an overkill, pain to support and will defo result in integration problems (exchanges may not follow OpenRTB specs strictly). Using constants (and rejecting anything, that comes from exchange/bidder and doesn't match those constants) is the safest way to go. Or even have smth like `TheType(X).IsValid() bool` or `TheType(X).Validate() error`, but don't force it when marshaling, should be up to lib consumer.

Also, I wanted to make/keep this lib as logic-less as possible - just data types.

That's my vision for current repo. If you need type-safety right now, or insist on (un)marshaler validation - just fork it.

**Comment by dbemiller** [comment]
ok. Thanks for the quick reply!
