### ISSUE TITLE
Proposal: separate Ext from core types 

### ISSUE THREAD

**Issue by dbemiller** [mxmCherry/openrtb#22]
I woke up this morning with an idea which I _think_ might be awesome. However, it'd be a fairly major change to this library... so let me know what you think.

The problem is the OpenRTB `Ext` fields. Since each Exchange is supposed to define their own, a core library like this is stuck typing them to be "arbitrary JSON." I think this all makes sense.

In practice, we pass these types throughout many layers of our code. So we need to `Unmarshal` the `Ext` fields once to validate input, and then decide between passing extra arguments with all our `Ext` structs, or else do the `Unmarshal` twice. Neither solution is great. It's actually a bit worse than that, because `Ext` means different things to different layers; we preprocess it so that one bidder can't read it and use the data to find out which other bidders are involved in the auction.

Enter.... embedded structs! I'm fairly new to Go, and have never seen a good use-case for these yet, but... I think this might be the first. Basically, it seems like we can do:

```
type Inner struct {
    Value int
}

type Outer struct{
    Inner
    Name string
}

func doThing(outer *Outer) {
    outer.Name // Is legal
    outer.Value // Is legal
}
```

So... how would you feel about decomposing the structs in this library? For example:

```
type CoreRequest struct {
  ... all Request fields _except_ for Ext go here ...
}

type Request struct {
  CoreRequest
  Ext    RawJSON
}
```

That way someone could import this library and define their own:

```
type MyRequest struct {
  CoreRequest
  Ext    MyStrictlyTypedExtHere
}
```

and get strictly-typed `Ext`, while still benefiting from all the other excellent spec-tracking you've done here :)

**Comment by dbemiller** [comment]
Should note: I have not tested this with `json.Marshal` and `json.Unmarhsal` yet, to see how it handles the embedded fields. I'm assuming it includes them and behaves sensibly.

**Comment by mxmCherry** [comment]
https://github.com/mxmCherry/openrtb/issues/22#issuecomment-369950406

Yep, it will work as you expect it to work.

---

But no, idea is not really viable - almost every Object has Ext field on it:

```
type BidRequestCore struct {
  ID string
  Test int8
  // and, basically, only simple fields, which are, roughly, 50% of all fields in BidRequest
}

type BidRequest struct {
  Imp []ImpWithCustomExt
  Site *SiteWithCustomExt
  // and every Object-type field - roughly, 50% of "code it yourself"
}
```

Even if Ext is usually set only on BidRequest, doing only BidRequestCore (and BidResponseCore) would make this lib look inconsistent.

So no:
- doing it properly (everything typed) - too much work for consumer, too inconvenient for 99% of consumers (they won't ever need/use it; and remaining 1% can fork and adapt the repo)
- doing it only for BidRequest/Response - partial solution, library would look weird and inconsistent

Previously, I had similar intent (typings): https://github.com/mxmCherry/openrtb/issues/8#issuecomment-273698172

But RawJSON/json.RawMessage appeared to be the most flexible thing.

Probably, the best (the only?) solution is to make some abstract object (wrapper) to drag it through all the data-transformation methods and convert to OpenRTB type at the end.

Close the issue if you agree with ^^

**Comment by dbemiller** [comment]
blah.... you're totally right, though I don't want to admit it :p.

Thanks for the explanation!
