### ISSUE TITLE
avoid []uint8

### ISSUE THREAD

**Issue by csyangchen** [mxmCherry/openrtb#3]
as mentioned in <http://stackoverflow.com/questions/14177862/how-to-jsonize-a-uint8-slice-in-go>,
`[]uint8` fields are json encoded into string.

Maybe replace `[]uint8` with `[]int`, or, to make things simpler, just replace all `uint*` with `int`?

**Comment by mxmCherry** [comment]
Changed all `uint8` types to `int8`.

You may now `import "gopkg.in/mxmCherry/openrtb.v1"` (https://github.com/mxmCherry/openrtb/releases/tag/v1.0.0).

Thanks for reporting!

P.S.: https://github.com/bsm/openrtb has lots of `int`s and tests :)
