### ISSUE TITLE
height and width in banner.go should not have omitempty set

### ISSUE THREAD

**Issue by afsheenb** [mxmCherry/openrtb#33]
Hello,

One of our demand partners has recently begin returning bid responses to us with banners where h and w are set to 0; it appears that we're discarding these fields completely, because the omitempty attribute. is set for them https://github.com/mxmCherry/openrtb/blob/master/banner.go#L26-L42 

```The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.```

These fields are defined as integers in the OpenRTB2.5 spec, and so 0 is a valid value for them: https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf

We've raised this as an issue with the upstream partner, but I'm flagging this issue as well as I believe it needs to be resolved upstream from them - it's unexpected that they would set h or w to 0, but it is legal according to the spec afaict...

Cheers,

--afsheen

**Comment by afsheenb** [comment]
I suspect the fix is similar to what was done here for the 'secure' field: https://github.com/mxmCherry/openrtb/issues/10 - let me know if that's right and I'll submit a pull request to change h and w to pointers.

**Comment by mxmCherry** [comment]
Umm, wait a sec.

Omitempty is just for marshalling, not for unmarshalling.

Unmarshaling `0` into `*uint64` should be just fine, you should just get a pointer to `uint64(0)`:

```go
	var banner openrtb.Banner

	if err := json.Unmarshal([]byte(`{ "w": 0, "h": 0 }`), &banner); err != nil {
		panic(err)
	}

	fmt.Printf("%#v %#v\n", banner.W, banner.H)   // (*uint64)(0xc000014260) (*uint64)(0xc000014268)
	fmt.Printf("%#v %#v\n", *banner.W, *banner.H) // 0x0 0x0
```

Works just as expected.

**Comment by mxmCherry** [comment]
I think, your partner has to explicitly set w/h:

```go
	banner := openrtb.Banner{
		W: openrtb.Uint64Ptr(0),
		H: openrtb.Uint64Ptr(0),
	}

	b, err := json.MarshalIndent(banner, "", "  ")
	if err != nil {
		panic(err)
	}

	println(string(b))
	// {
	//   "w": 0,
	//   "h": 0
	// }
```

Here's a PR/discussion: https://github.com/mxmCherry/openrtb/pull/16

**Comment by afsheenb** [comment]
Thanks for the quick response (and the clarification!) 

More details, in case they're relevant: we're connecting to the partner using [prebid-server](https://github.com/prebid/prebid-server), sending requests to a prebid-server instance that are in turn forwarded to the demand partner's endpoint. Adding debug logging to the demand partner's adapter we've seen these fields are omitted when the response from the demand partner has them set to 0 (as confirmed by sending an HTTP POST directly to the demand partner's RTB endpoint without prebid-server in between). 

I'll continue to investigate this on our end, and will close this ticket now - aplogies for the red herring.
