### ISSUE TITLE
Native response asset id lost with omitempty

### ISSUE THREAD

**Issue by rokostik** [mxmCherry/openrtb#44]
Hey,

if the ID of a native response asset (https://github.com/mxmCherry/openrtb/blob/master/native1/response/asset.go#L21) has a value of 0 it's lost when marshalling. 

Looking through other similar issues (https://github.com/mxmCherry/openrtb/issues/33) in this repo the fix would probably to change it to a pointer?

**Comment by mxmCherry** [comment]
Merged and released as https://github.com/mxmCherry/openrtb/releases/tag/v15.0.0

Thanks for PR-ing it!
