### ISSUE TITLE
`user.keywords` field should be list (`[]string`)

### ISSUE THREAD

**Issue by csyangchen** [mxmCherry/openrtb#5]
`user.keywords` field should be list (`[]string`)

**Comment by mxmCherry** [comment]
No, it shouldn't.

https://github.com/openrtb/OpenRTB/blob/master/OpenRTB-API-Specification-Version-2-3-1-FINAL.pdf

> 3.2.13 Object: User
> ...
> keywords string **Comma separated** list of keywords, interests, or intent.

Please, correct me if I'm missing something or close this issue.

**Comment by csyangchen** [comment]
em, my bad. it seems some adx doesn't strictly follow this spec.
