### ISSUE TITLE
OpenRTB 2.5, Regs.COPPA field - make it ptr? 

### ISSUE THREAD

**Issue by chobhe** [mxmCherry/openrtb#50]
inside regs.go, COPPA should be a pointer so it's value of 0 doesn't get omitted when JSON marshalling?

**Comment by mxmCherry** [comment]
Discussion to be held in PR comments: https://github.com/mxmCherry/openrtb/pull/51#issuecomment-1186219644

If it's worth the effort - it'll get merged/released (and release approach - alpha or next stable version with smaller changeset - is also subjecct to discuss).

**Comment by mxmCherry** [comment]
Closing this - sorry, kept all the conversation in the PR: https://github.com/mxmCherry/openrtb/pull/51#issuecomment-1195614836

Looks like it's not a "must" at this point, can reopen if anything changes.
